#ifndef _PAGE_TYPE
#define _PAGE_TYPE

#define PAGE_TYPE_PHYSICAL_MEMORY_MAP 0x0F
#define PAGE_TYPE_PHYSICAL_MEMORY_MAP_SECTION 0x0E
#define PAGE_TYPE_PAGE_DIRECTORY 0x09
#define PAGE_TYPE_PAGE_TABLE 0x08
#define PAGE_TYPE_USER_ALLOCATED 0x07
#define PAGE_TYPE_KERNEL_ALLOCATED 0x06
#define PAGE_TYPE_HARDWARE_RESERVED 0x01
#define PAGE_TYPE_UNALLOCATED 0x00
#define PAGE_TYPE(t) ((t)&0x0F)

#endif // _PAGE_TYPE
